import React from "react";
import type { NextPage } from "next";
import Head from "next/head";

import styled from "styled-components";
import Navbar from "../components/Navbar";
import Products from "../components/Products";

const Container = styled.div``;

const Home: NextPage = () => {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <Products />
    </Container>
  );
};

export default Home;
